version: '3'
services:
  my_service:
    image: inbound-api
    build: .
    env_file:
      - .env
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app 
    expose:
      - 9001

  caddy:
    image: caddy:2.8.5-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    # depends_on:
    #   - api

volumes:
  caddy_data:
  caddy_config: