name: Backend Tests

on:
  push:
    branches: [dev,feat/github-actions] #remove the temp feat/github-actions branch after the PR is merged
  

  # pull_request:
  #   branches: [ dev,feat/github-actions]
     #remove the temp feat/github-actions branch after the PR is merged

permissions:
  contents: read

jobs:
  tests:
    name: Vitest Tests
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/inbound_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Run Vitest
        run: npm test